import { IToastIds } from '../../interfaces/errors/ToastIds';

export const toastIds: IToastIds = {
  UNKNOWN: 0,
  FORBIDDEN: 1,
  INTERNAL_ERROR: 2,
  USER_EXISTS: 3,
  USER_PASSWORD_DONT_MATCH: 4,
  MISSING_PARAMETERS: 5,
  DEFAULT_TOAST: 6,
  NO_DATA_RESPONSE: 7,
  UNABLE_TO_DELETE_TITLE: 8,
  ALREADY_IN_GAME: 9,
  ACHIEVEMENT_ALREADY_OBTAINED: 10,
};
